import type { ConversationPipeline, LogLine } from '@/types/pipeline'
import type { RefinementResult } from '@/types/requirements'

export const MOCK_DEMO_NLP_RESULT: RefinementResult = {
  refining_id: 'ref-001-demo',
  feature: 'AEB (Autonomous Emergency Braking)',
  source_file: 'requirements_v2.xlsx',
  pipeline_status: { status: 'ready', reason: '', blocked_by: [] },
  summary: {
    total_raw: 47,
    total_refined: 44,
    total_removed: 3,
    total_conflicts: 2,
    total_overlaps: 4,
  },
  requirements: [
    {
      id: 'REQ-001',
      original: 'System shall detect pedestrians within 50 meters at highway speeds',
      refined: 'System shall detect pedestrians within 50 m at speeds ≥80 km/h',
      issues_found: [],
      status: 'refined',
      overlap_with: ['REQ-002'],
      conflict_flag: false,
      conflict_id: null,
      complexity: 'HIGH',
      complexity_justification: 'Requires sensor fusion and ML model inference at highway speeds',
      num_scenarios: 5,
    },
    {
      id: 'REQ-002',
      original: 'Pedestrian detection range shall be 45-55 meters',
      refined: 'Pedestrian detection range: 45–55 m nominal, ±2 m tolerance',
      issues_found: [],
      status: 'refined',
      overlap_with: ['REQ-001'],
      conflict_flag: false,
      conflict_id: null,
      complexity: 'HIGH',
      complexity_justification: 'Overlaps with REQ-001 detection range requirement',
      num_scenarios: 5,
    },
    {
      id: 'REQ-003',
      original: 'Braking response time shall not exceed 250 ms from detection',
      refined: 'Braking response latency ≤250 ms from sensor reading to actuator command',
      issues_found: ['Ambiguous: sensor reading vs. system detection time'],
      status: 'refined',
      overlap_with: [],
      conflict_flag: true,
      conflict_id: 'CONF-001',
      complexity: 'MEDIUM',
      complexity_justification: 'Requires hard real-time guarantees, conflicts with REQ-004',
      num_scenarios: 8,
    },
    {
      id: 'REQ-004',
      original: 'System reaction time must be less than 200 ms',
      refined: 'System reaction time <200 ms (estimated hardware latency budget)',
      issues_found: ['Conflicts with REQ-003: 250 ms vs. 200 ms'],
      status: 'unchanged',
      overlap_with: [],
      conflict_flag: true,
      conflict_id: 'CONF-001',
      complexity: 'MEDIUM',
      complexity_justification: 'Stricter than REQ-003, may be infeasible',
      num_scenarios: 8,
    },
    {
      id: 'REQ-005',
      original: 'False positive rate shall be minimized below 5 percent',
      refined: 'False positive rate <5% in urban scenarios, <3% on highway',
      issues_found: [],
      status: 'refined',
      overlap_with: ['REQ-006'],
      conflict_flag: false,
      conflict_id: null,
      complexity: 'HIGH',
      complexity_justification: 'Requires extensive validation dataset and ML tuning',
      num_scenarios: 12,
    },
    {
      id: 'REQ-006',
      original: 'False positive suppression in rain must be effective',
      refined: 'FP rate in rain conditions: <2% (sensor filtering enabled)',
      issues_found: [],
      status: 'refined',
      overlap_with: ['REQ-005'],
      conflict_flag: false,
      conflict_id: null,
      complexity: 'MEDIUM',
      complexity_justification: 'Weather-specific edge case of REQ-005',
      num_scenarios: 6,
    },
    {
      id: 'REQ-007',
      original: 'AEB system shall not trigger on road markings or shadows',
      refined: 'Environmental feature rejection: road markings, shadows, reflections >99% suppression',
      issues_found: [],
      status: 'refined',
      overlap_with: ['REQ-008'],
      conflict_flag: false,
      conflict_id: null,
      complexity: 'MEDIUM',
      complexity_justification: 'Common failure mode in vision-based detection',
      num_scenarios: 10,
    },
    {
      id: 'REQ-008',
      original: 'System must reject false detections from reflections and wet surfaces',
      refined: 'Reflection rejection rate >98%, wet surface disambiguation enabled',
      issues_found: [],
      status: 'refined',
      overlap_with: ['REQ-007'],
      conflict_flag: false,
      conflict_id: null,
      complexity: 'MEDIUM',
      complexity_justification: 'Overlaps with environmental feature rejection',
      num_scenarios: 8,
    },
    {
      id: 'REQ-009',
      original: 'Braking deceleration shall be 8 m/s² for AEB emergency stop',
      refined: 'Emergency AEB deceleration: 7.5–8.5 m/s² (friction-limited)',
      issues_found: [],
      status: 'refined',
      overlap_with: [],
      conflict_flag: false,
      conflict_id: null,
      complexity: 'MEDIUM',
      complexity_justification: 'Vehicle dynamics model validation required',
      num_scenarios: 6,
    },
    {
      id: 'REQ-010',
      original: 'System shall apply full braking within 300 ms of detection',
      refined: 'Full braking application time: ≤300 ms from detection event',
      issues_found: [],
      status: 'unchanged',
      overlap_with: [],
      conflict_flag: false,
      conflict_id: null,
      complexity: 'MEDIUM',
      complexity_justification: 'Dependent on brake actuator performance',
      num_scenarios: 4,
    },
    {
      id: 'REQ-011',
      original: 'System performance at night with low visibility',
      refined: 'Low-light detection range ≥25 m (IR sensor fallback if available)',
      issues_found: ['Vague: "low visibility" not quantified initially'],
      status: 'refined',
      overlap_with: [],
      conflict_flag: false,
      conflict_id: null,
      complexity: 'HIGH',
      complexity_justification: 'Requires sensor fusion (visible + IR)',
      num_scenarios: 7,
    },
    {
      id: 'REQ-012',
      original: 'Pedestrian classification shall distinguish adults from children',
      refined: 'Height classification: <1.2 m (child), 1.2–2.0 m (adult)',
      issues_found: [],
      status: 'refined',
      overlap_with: [],
      conflict_flag: false,
      conflict_id: null,
      complexity: 'HIGH',
      complexity_justification: 'ML model must learn size-based discrimination',
      num_scenarios: 9,
    },
    {
      id: 'REQ-013',
      original: 'AEB shall not activate when vehicle speed is below 5 km/h',
      refined: 'AEB inhibit threshold: speed <5 km/h (low-speed creep exempt)',
      issues_found: [],
      status: 'unchanged',
      overlap_with: [],
      conflict_flag: false,
      conflict_id: null,
      complexity: 'LOW',
      complexity_justification: 'Simple speed comparison',
      num_scenarios: 3,
    },
    {
      id: 'REQ-014',
      original: 'Driver override shall deactivate emergency braking',
      refined: 'Driver brake pedal input overrides AEB within 50 ms of engagement',
      issues_found: [],
      status: 'refined',
      overlap_with: [],
      conflict_flag: false,
      conflict_id: null,
      complexity: 'LOW',
      complexity_justification: 'Standard input prioritization logic',
      num_scenarios: 5,
    },
    {
      id: 'REQ-015',
      original: 'AEB status shall be visible on dashboard',
      refined: 'AEB active/ready status displayed on driver info cluster (250 ms update)',
      issues_found: [],
      status: 'refined',
      overlap_with: [],
      conflict_flag: false,
      conflict_id: null,
      complexity: 'LOW',
      complexity_justification: 'Simple HMI integration',
      num_scenarios: 2,
    },
  ],
  removed: [
    {
      id: 'REMOVED-001',
      original: 'System shall use only visible light camera sensors',
      reason: 'Superseded by multi-sensor architecture (visible + thermal)',
    },
    {
      id: 'REMOVED-002',
      original: 'Maximum latency 100 ms',
      reason: 'Unrealistic given sensor processing pipeline; revised to REQ-003',
    },
    {
      id: 'REMOVED-003',
      original: 'Detection accuracy above 99.5%',
      reason: 'Too vague; replaced with scenario-specific FP/FN rates',
    },
  ],
  conflicts: [
    {
      conflict_id: 'CONF-001',
      requirements: ['REQ-003', 'REQ-004'],
      description:
        'REQ-003 specifies 250 ms braking latency, but REQ-004 demands <200 ms system reaction time. This creates an infeasible hard real-time constraint. Recommend clarifying measurement points (sensor input vs. brake command) and aligning latency budget.',
    },
    {
      conflict_id: 'CONF-002',
      requirements: ['REQ-001', 'REQ-002'],
      description:
        'REQ-001 states "within 50 meters" while REQ-002 specifies "45–55 meters". Interpret REQ-002 as refinement of REQ-001 detection range nominal, accept both.',
    },
  ],
}

export const MOCK_DEMO_PIPELINE: ConversationPipeline = {
  stage: 1,
  round: 1,
  entryStage: 1,
  agentMessage: null,
  nlp: 'awaiting',
  scenario: 'idle',
  execution: 'idle',
  report: 'idle',
  engineerInput: 'Loaded from: requirements_v2.xlsx (47 raw requirements)',
  nlpResult: MOCK_DEMO_NLP_RESULT,
  nlpProgress: {},
  scenarioResult: null,
  executionResult: null,
  reportResult: null,
  priorRounds: [],
}
